#!/bin/bash
set -eu
NAME="stumpecho"

if [ "$#" -ne "2" ]
then
    echo "Usage: $NAME <summary> <body>"
    exit 1
fi

summary="$1"
body="$2"

stumpish eval "(echo \"^2*$summary
^7*$body\")" > /dev/null
